spring.application.name=EMMA

# Servidor de la aplicacion (Puerto por defecto)
server.port=8080

# Conexion a MySQL (Ajusta tu usuario y contrasena de MySQL local)
spring.datasource.url=jdbc:mysql://shortline.proxy.rlwy.net:21689/railway?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=qNoLLqJQhhMJQVokUWrAzJISkFyyLxOk

# Configuracion de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Desactivar el cache de Thymeleaf para ver los cambios sin reiniciar
spring.thymeleaf.cache=false