spring.application.name=EMMA-1

# Servidor de la aplicación (Puerto por defecto)
server.port=8080

# Conexión a MySQL (Ajusta tu usuario y contraseña de MySQL local)
spring.datasource.url=jdbc:mysql://localhost:3306/EmmaDesiTuti?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Desactivar el caché de Thymeleaf para ver los cambios en las pantallas sin reiniciar
spring.thymeleaf.cache=false